# Generated by Django 5.1 on 2024-08-25 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminChoices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Demographic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Unknown Demographic", max_length=255, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Unknown Genre", max_length=255, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Unknown Rating", max_length=255, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Unknown Source", max_length=255, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Studio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Unknown Studio", max_length=255, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TypeOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Unknown Type", max_length=255, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneralData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_id", models.IntegerField(default=-1, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("name_english", models.CharField(max_length=255)),
                ("score", models.FloatField()),
                ("ranked", models.IntegerField()),
                ("popularity", models.IntegerField()),
                ("members", models.IntegerField()),
                ("synopsis", models.TextField()),
                ("total_episodes", models.FloatField()),
                ("premiered", models.CharField(max_length=100)),
                ("duration_per_ep", models.CharField(max_length=100)),
                ("scored_by", models.FloatField()),
                ("favorites", models.IntegerField()),
                ("aired", models.CharField(max_length=100)),
                (
                    "imagelink",
                    models.CharField(default="un-available", max_length=255, null=True),
                ),
                ("watching", models.IntegerField()),
                ("completed", models.IntegerField()),
                ("on_hold", models.IntegerField()),
                ("dropped", models.IntegerField()),
                ("plan_to_watch", models.IntegerField()),
                ("total", models.IntegerField()),
                ("scored_10_by", models.FloatField()),
                ("scored_9_by", models.FloatField()),
                ("scored_8_by", models.FloatField()),
                ("scored_7_by", models.FloatField()),
                ("scored_6_by", models.FloatField()),
                ("scored_5_by", models.FloatField()),
                ("scored_4_by", models.FloatField()),
                ("scored_3_by", models.FloatField()),
                ("scored_2_by", models.FloatField()),
                ("scored_1_by", models.FloatField()),
                (
                    "demographic",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anime.demographic",
                    ),
                ),
                (
                    "genre",
                    models.ManyToManyField(related_name="animes", to="anime.genre"),
                ),
                (
                    "rating",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anime.rating",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anime.source",
                    ),
                ),
                (
                    "studio",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anime.studio",
                    ),
                ),
                (
                    "typeof",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anime.typeof",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Saved_anime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "anime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anime.generaldata",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "anime")},
            },
        ),
    ]
